import * as childProcess from "node:child_process";
import * as fs from "node:fs/promises";
import * as path from "node:path";

const reset = process.argv.includes("--reset");
const outputPath = path.join(import.meta.dir, "../native/embedded-addon.js");
const packageJsonPath = path.join(import.meta.dir, "../package.json");
const nativeDir = path.join(import.meta.dir, "../native");

const stubContent = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 */

/** @type {EmbeddedAddon|null} */
export const embeddedAddon = null;
`;

if (reset) {
	await Bun.write(outputPath, stubContent);
	process.exit(0);
}

interface CandidateAddon {
	variant: "modern" | "baseline" | "default";
	filename: string;
}

async function fileExists(filePath: string): Promise<boolean> {
	try {
		await fs.stat(filePath);
		return true;
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code === "ENOENT") return false;
		throw err;
	}
}

/**
 * Validate that a `.node` binary exports the expected version sentinel.
 * For the current platform, we try to load it directly (most reliable).
 * For cross-compiled binaries, we fall back to `strings` or `nm` to probe
 * for the sentinel symbol name in the binary.
 */
function validateAddonSentinel(candidatePath: string, expectedSentinel: string, platformTag: string): void {
	const isCurrentPlatform = `${process.platform}-${process.arch}` === platformTag;

	// 1. Try direct load on current platform — most reliable.
	if (isCurrentPlatform) {
		try {
			const addon = require(candidatePath) as Record<string, unknown>;
			if (typeof addon[expectedSentinel] === "function") {
				return;
			}
			// Sentinel missing — fall through to CLI probes for a better error.
		} catch {
			// Load failed (e.g. missing deps) — fall through to CLI probes.
		}
	}

	// 2. Try `nm` (works on unstripped ELF/Mach-O).
	try {
		const result = childProcess.spawnSync("nm", ["-D", candidatePath], {
			encoding: "utf-8",
			timeout: 5000,
		});
		if (result.status === 0 && result.stdout.includes(expectedSentinel)) {
			return;
		}
	} catch {
		// nm not available or failed.
	}

	// 3. Try `strings` (works on stripped binaries because napi embeds the
	//    js_name as a string literal).
	try {
		const result = childProcess.spawnSync("strings", [candidatePath], {
			encoding: "utf-8",
			timeout: 5000,
		});
		if (result.status === 0 && result.stdout.includes(expectedSentinel)) {
			return;
		}
	} catch {
		// strings not available or failed.
	}

	// 4. Nothing confirmed the exact sentinel.
	if (isCurrentPlatform) {
		throw new Error(
			`Native addon ${candidatePath} does not export the expected version sentinel \`${expectedSentinel}\`. ` +
				"The .node file on disk is stale (built before the version bump). " +
				"Rebuild with: bun --cwd=packages/natives run build",
		);
	}

	console.warn(
		`Warning: Could not verify version sentinel in ${candidatePath} for cross-compiled target ${platformTag}. ` +
			"Ensure the native addon was rebuilt after the version bump.",
	);
}

const targetPlatform = Bun.env.TARGET_PLATFORM || process.platform;
const targetArch = Bun.env.TARGET_ARCH || process.arch;
const platformTag = `${targetPlatform}-${targetArch}`;
const packageJson = (await Bun.file(packageJsonPath).json()) as { version: string };
const expectedSentinel = `__piNativesV${packageJson.version.replace(/[^A-Za-z0-9]/g, "_")}`;

const candidates: CandidateAddon[] =
	targetArch === "x64"
		? [
				{ variant: "modern", filename: `pi_natives.${platformTag}-modern.node` },
				{ variant: "baseline", filename: `pi_natives.${platformTag}-baseline.node` },
			]
		: [{ variant: "default", filename: `pi_natives.${platformTag}.node` }];

const available: CandidateAddon[] = [];
for (const candidate of candidates) {
	const candidatePath = path.join(nativeDir, candidate.filename);
	if (await fileExists(candidatePath)) {
		validateAddonSentinel(candidatePath, expectedSentinel, platformTag);
		available.push(candidate);
	}
}

if (available.length === 0) {
	const expected = candidates.map(candidate => `  - ${candidate.filename}`).join("\n");
	throw new Error(`No native addons found for ${platformTag}. Expected one of:\n${expected}`);
}

const imports = available
	.map(
		(candidate, index) =>
			`import addonPath${index} from ${JSON.stringify(`../native/${candidate.filename}`)} with { type: "file" };`,
	)
	.join("\n");

const files = available
	.map(
		(candidate, index) =>
			`\t\t{ variant: ${JSON.stringify(candidate.variant)}, filename: ${JSON.stringify(candidate.filename)}, filePath: addonPath${index} },`,
	)
	.join("\n");

const content = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 */

${imports}

export const embeddedAddon = {
\tplatformTag: ${JSON.stringify(platformTag)},
\tversion: ${JSON.stringify(packageJson.version)},
\tfiles: [
${files}
\t],
};
`;

await Bun.write(outputPath, content);
